baseURL = ""
languageCode = "en-us"
relativeURLs = true
theme = "sourgough-starter"
title = "Andrew John Buggee"
[markup.goldmark.renderer]
unsafe = true
[[menu.about]]
identifier = "ordcidid"
name = "OrcidID"
pre = "fab fa-orcid"
url = ""
[[menu.about]]
identifier = "researchgate"
name = "ResearchGate"
pre = "fab fa-researchgate"
url = ""
[[menu.about]]
identifier = "googlescholar"
name = "Google Scholar"
pre = "fas fa-graduation-cap"
url = "https://scholar.google.com/citations?user=yjGwDt0AAAAJ&hl=en"
[[menu.bot]]
identifier = "github"
name = "Github"
pre = "fab fa-github"
url = "https://github.com/andrewjbuggee/"
[[menu.bot]]
identifier = "linkedin"
name = "LinkedIn"
pre = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/andrew-buggee-69830a191/"
[[menu.link]]
identifier = "email"
name = "andrewbuggee@gmail.com"
url = "mailto:andrewbuggee@gmail.com"
[[menu.link]]
identifier = "resume"
name = "resume"
url = ""
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
[params]
backgroundPath = "/uploads/a39517c3-87f3-441e-ad90-ab5e55bc3dc7_1_201_a.jpeg"
css = ["css/sourgough.css"]
dimensionCitations = true
dimensionsID = "XXXX"
dimensionsLink = false
footerOffset = -60
googleScholar = "XXXX"
scholarLink = true
scopusID = "XXXX"
scopusLink = false
[taxonomies]
authors = "authors"
