baseURL = "https://sourgough.mrph.dev"
languageCode = "en-us"
relativeURLs = true
theme = "sourgough-starter"
title = "Your Name"
[markup.goldmark.renderer]
unsafe = true
[[menu.about]]
identifier = "googlescholar"
name = "Google Scholar"
pre = "fas fa-graduation-cap"
weight = 1
[[menu.about]]
identifier = "researchgate"
name = "ResearchGate"
pre = "fab fa-researchgate"
weight = 2
[[menu.about]]
identifier = "ordcidid"
name = "OrcidID"
pre = "fab fa-orcid"
weight = 3
[[menu.bot]]
identifier = "linkedin"
name = "LinkedIn"
pre = "fab fa-linkedin-in"
url = "https://www.linkedin.com/in/andrew-buggee-69830a191/"
weight = 1
[[menu.bot]]
identifier = "github"
name = "Github"
pre = "fab fa-github"
url = "https://github.com/andrewjbuggee"
weight = 2
[[menu.link]]
identifier = "resume"
name = "resume"
weight = 1
[[menu.link]]
identifier = "email"
name = "email@example.com"
url = "mailto:andrewbuggee@gmail.com"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 1
[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 2
[params]
backgroundPath = "images/SA_back.png"
css = ["css/sourgough.css"]
dimensionCitations = true
footerOffset = -60
scholarStats = false
[taxonomies]
authors = "authors"
